### ISSUE TITLE
Dark Brotherhood Services

### ISSUE THREAD

**Issue by Hellmasker10** [Interkarma/daggerfall-unity#1377]
Not a major issue, but... the old Lady in a Brotherhood Guildhall should sell me soulgems, but it says it's not yet implemented... now according to the roadmap, guild services 'should' be done... was this an oversight or is it just planned for a later release? Just curious, as I couldn't find any info about it :)

(and yes, I might be a little bit annoying here... but I stumbled upon this project just a few days ago and I do have a blast... feels so much better than the original :D )

**Comment by ajrb** [comment]
That's not really in the bug report format, could you post things like this over in the Help section of the DFU forums please? It will then be ascertained whether it is a bug and a issue raised here if so. I think that's the process @Interkarma wants but I've been quite busy so maybe I misunderstood. I will let him say more about it.. :)

Anyway a savefile that I can load up would be good to help be dev and test. I think though that soul gem merchants haven't been done since soul gems were not really implemented when I did this stuff.

**Comment by Hellmasker10** [comment]
[SAVE3.zip](https://github.com/Interkarma/daggerfall-unity/files/3452752/SAVE3.zip)

Here's the savefile right in front of the NPC in question :)

And yeah, I probably should make an account at the forums if I find out more stuff... Sorry for that!

**Comment by ajrb** [comment]
@TheLacus how do I add labels? This is more than a question, the service has been overlooked and I need to implement it.

**Comment by TheLacus** [comment]
I recently started to help Interkarma with handling PRs and issues, this is why i can add labels. I'll change to `bug` if you prefer. 

@Interkarma Maybe we need something like `unimplemented`?

**Comment by ajrb** [comment]
Implemented it and submitted a PR. Needs testing for Temple of Arkay as well since they also offer this service.
