### ISSUE TITLE
Macro %di expansion can fail and crash the game

### ISSUE THREAD

**Issue by df-ferital** [Interkarma/daggerfall-unity#1383]
**Bug description**
Macro %di expansion can fail and crash the game.

**To Reproduce**
1. Load the attached save (courtesy of Interkarma, save provided on the forum thread regarding %loc issue)
2. Using the console, activate the NPC know everything flag to easily reproduce the issue.
3. Ask any NPC about Evelyna Kingsmith in **Tell me about only** (not in Where is people)
4. At some point, when the anwer uses %di, the game should crash.

The problem lies at line 230 in QuestMCP.cs in `LocationDirection` method: `LastPlaceReferenced ` is not supposed to be null there but it is with this particular quest.

**Expected behavior**
The game should never crash :)

**Desktop**
 - OS: Windows 10
 - Version 1803

**Additional context**
Discovered while testing my fix for %loc expansion...

[SAVE675.zip](https://github.com/Interkarma/daggerfall-unity/files/3458173/SAVE675.zip)

**Comment by Nystul-the-Magician** [comment]
will take a look but after fixing the discovery issues - so please be patient

**Comment by JorisVanEijden** [comment]
I noticed 2 problems with the %di functionality.
1. It doesn't check if there is actually a location referenced in the quest. (crash)
2. If the location from the quest is the same location you're in it doesn't work. (text like "it's ... never mind ... of here")

I created a PR (#1418) to solve these.
1. by checking if there is a referenced location.
and by adding a reference to a persons location when the quest mentions a person.
2. by getting the direction to the building inside the location.

**Comment by Nystul-the-Magician** [comment]
thanks for taking a look!

**Comment by JorisVanEijden** [comment]
Note, the offending quest text is `_contact_, eh? A mysterious =contact_ who operates out of __contact_, %di of here.`

As per InterKarma request I'm splitting this into multiple PRs:
#1425 for the crash
Supplied savefile will no longer crash but will say `Evelyna Kingsmith, eh? A mysterious blue-cloaked woman who operates out of The Ashwing Residence, ... never mind ... of here.`
#1426  for adding the contact's location to the quest
NPC will say `Evelyna Kingsmith, eh? A mysterious blue-cloaked woman who operates out of The Ashwing Residence, never mind ... of here.` Note the triple dots that are gone. This is because the location is now known, but the same as where the player is so it can't calculate a direction.

Originally (in #1418) I used a separate code path from TalkManager to get the direction to a building if the referenced location was a building in the current location. But now I'm not so sure that that was the right approach. It definitely works, with the supplied save I get told `Evelyna Kingsmith, eh? A mysterious blue-cloaked woman who operates out of The Ashwing Residence, north of here.` but it feels like there has to be a more efficient way.

I also added a different "error" for getting the direction to a location you're already in. Supply "in the vicinity" to make texts like "...Residence, in the vicinity of here." but that is definitely not DF classic, and also leads to texts like ".. a long way to the in the vicinity" ;)
Not sure how to proceed here.

**Comment by Interkarma** [comment]
Resolved by #1425 and #1426. Thank you @JorisVanEijden. :)
