### ISSUE TITLE
0.10.4 Dark Brotherhood contact building not being marked on map again

### ISSUE THREAD

**Issue by Interkarma** [Interkarma/daggerfall-unity#1408]
Reported by BansheeXYZ in below forum topic. Might be something we missed @Nystul-the-Magician 

https://forums.dfworkshop.net/viewtopic.php?f=24&t=2493&p=29006#p29006

**Comment by Nystul-the-Magician** [comment]
whats interesting about this is:
i deleted the named residences from the discovery savegame data for the location. Then nothing is revealed on map as expected. When talking to the npcs about the residence (Kingsley Residence) and getting it marked on the map it gets marked as Wickston Residence - so it might be a problem with either:
- different residence name resolving in quests and discovery system
- or, a savegame from an older build where the residence name was resolved differently back then when quest started
@Interkarma: would you like to assist me with helping to track this down since I am a bit unsure how to proceed here

**Comment by Interkarma** [comment]
Thanks for taking a look, Nystul! I'm starting to suspect second case, but will try to clarify when I can. Will take a closer look when I can. I appreciate your help. :)

**Comment by Interkarma** [comment]
Have confirmed with Banshee this is a fresh save. As you're more familiar with talk system, are you able to let me know where NPC fails to mark on map in talk UI, and what info it's failing to find? I suspect now this might be related to automatic NPCs not being correctly placed by quest system. If you're at least able to confirm where things fail in talk UI, I can backtrack from there.

Thank you for any help you can give. :)

**Comment by Nystul-the-Magician** [comment]
nothing fails building is added to map as expected just the name does not match the name that appears in log - so I suspect discovery system resolves to different name than quest

you can easily check by first removing the discovery data from savegame folder and then let an npc mark the residence on the map - it will appear but the name will be different

**Comment by Interkarma** [comment]
Interesting, thank you for reinforcing. I will see what I can do. :)

**Comment by Interkarma** [comment]
This appears have been resolved. Closing.
