### ISSUE TITLE
Witch Coven Quest: Vampires and Werewolfes despawn

### ISSUE THREAD

**Issue by EPNW** [Interkarma/daggerfall-unity#1433]
**Describe the bug**
[In the witch coven quests where you are to deliver a potion to a mages guild](https://en.uesp.net/wiki/Daggerfall:A_Special_Mixture) vampires and werewolfes should spawn at night AND for the first you fasttravel somewhere. So if you arive at daytime the will spawn, too (I dont know if thats intended but thats not the strange part).

Now I save the game (since I wanted to get infected by a vampire), and got killed. I reloaded the save, but the vampires and werewolfes were gone.

The screenshot of the attached save shows that there should be a vampire, but if I load the save, shes gone.

**To Reproduce**
Load the Save [SAVE282.zip](https://github.com/Interkarma/daggerfall-unity/files/3507094/SAVE282.zip)

**Expected behavior**
There should be a vampire

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/30860236/63124897-a67cfd00-bfac-11e9-9630-c2c5b9c80875.jpg)

**Desktop:**
 - OS: Windows
 - Version 0.10.3

IMPORTANT EDIT:
If I load a save with vampires and its night, they are there, as expected. It seems the despawning only appears if I load a day save. I will try to find a save at night to prove this, might take a while though.

Edit2:
As promised I found a save at night time. As you can see in the second screenshot, there is a vampire, and if you load the [SAVE270.zip](https://github.com/Interkarma/daggerfall-unity/files/3521354/SAVE270.zip), she will attack you.

![Screenshot](https://user-images.githubusercontent.com/30860236/63360071-10f7b980-c36e-11e9-93ea-031f28543578.jpg)

Edit3:
It seems, according to uesp.net that the vampires  and lycanthropes should not spawn after the first fast travel, but in the first night there sould be a popup. This means that the vampire in the screenshot should never even have spawned in the first place... This does not explain the despawning though?

**Comment by Kiel97** [comment]
Maybe it's not related to the vampire quest but I have noticed sometimes city guards are despawning on save file load when trying to bash door at night.
I have also noticed when player stops loitering after 6 or 7PM civilians remain but when you lose sight on them and then try to look at them, they are gone.

**Comment by EndlessVoid1** [comment]
I'm unsure of the gritty details of how daggerfall unity was implemented - but from a implementers perspective: It seems like there is some type of logic which dictates that certain creatures are not allowed to exist during the day. I'm thinking maybe the cycles of the day/night are global variables of some sort that are persistent across all of daggerfall unity and the implementation of creatures like vampires/anything that shouldn't be allowed in the sun (at the very least from what the quest said) uses said global variables in another piece of logic, attached to those creatures, that doesn't allow them to exist. Maybe, implemented by de-spawning them or something. Or maybe there's global logic that is directly connected to how day/night was implemented. I'm unsure. 

Either which way you look at it: The vampires probably automatically spawn, even during the day. It seems because of that, that vampires don't take damage in the sun (as they aren't expected to even exist, I assume) - which probably rules that out. And because it only happens upon reloading... I'm thinking that upon reloading, it 'reapplies' or something to that nature which makes the game execute those lines of code - whatever implementation they may be. Thus, causing the disappearance upon reloading. 

This is purely speculation, I haven't looked deep into the systems of daggerfall unity and as said have no idea how it was initially implemented. 

Oh, yeah, I also just realized that this is probably in bug status because the vampires spawn the first time you travel anywhere and the quest doesn't say that happens. Yeah, only thing I could think is someone directly scripted that to happen or accidently as a result of some type of scripting logic, lol. 

Also, why has there been like zero discussion on this topic? I'm assuming it's because I'm completely misunderstanding how quests are handled both in original daggerall and daggerfall unity that makes this either A. Unfixable, or B. Extremely insignificant compared to other issues/not worth the effort and time (as it would be difficult) for something not very critical.

**Comment by EndlessVoid1** [comment]
I was digging and finally found where the quest was - I'm unsure the format that the quests use: Are they like scripts? If so, then there isn't anything accounting for them spawning when you first travel somewhere other than if it was right time period for them to spawn in the first place - it seems. 

As far as them disappearing... well, I finally found where the vampire entity was accounted for in the files and I don't think it said anything about disappearing when the sun comes out. Possibly, it isn't on the actual entity but the scripts for spawning entities in general? I'd have to do more digging.

**Comment by Interkarma** [comment]
I wasn't able to get vampires or werewolves to spawn during the day. That might be an edge case of some kind. I've noted the behaviour of "repeat until" task in this quest is inconsistent, so likely an emulation problem there.

Looking in save data for first save, there's no vampire present to load, which means it never saved that vampire despite being visible in the screenshot. Saving and loading with the enemies at night all restore as expected, and this data is definitely present in second save.

While I wasn't able to reproduce exact issue in bug report, there's definitely something inconsistent about "repeat until" task here that bears further investigation. That might also be behind the edge case of vampire spawning improperly and not saving correctly.
