### ISSUE TITLE
Main Story (The Emperor's Courier)

### ISSUE THREAD

**Issue by Ajanddino** [Interkarma/daggerfall-unity#1438]
During the main story quest "The Emperor's Courier" When I have to report back to Mynisera she isn't there. I can finish the quest but can't turn it in I'm at the point where I could talk to the guard then go to finish the quest. I'm using windows 10 and running daggerfall unity 0.10.4. Thanks

My save
[SAVE0.zip](https://github.com/Interkarma/daggerfall-unity/files/3513717/SAVE0.zip)

![image](https://user-images.githubusercontent.com/44139351/63232042-ed0f6900-c1f1-11e9-9a23-a6eabbc2e12d.png)

**Comment by Interkarma** [comment]
Mynisera isn't available because you also have Sx013 ([Mynisera's Letters](https://en.uesp.net/wiki/Daggerfall:Mynisera's_Letters)) active. Mynisera will be unavailable while this quest is active.

Because of time constraints, you won't be able to go back and hand this in before losing your time window with the courier. Here's how you can complete both:

1. From your save, visit the courier at Palace. This removes the time pressure from this quest.
2. Travel back to Castle Daggerfall and speak with Aubk-i first to hand in Mynisera's letters.
3. Leave Daggerfall and travel around for a few weeks to let Mynisera's Letters expire and Mynisera will return to her normal place.
4. Revisit Castle Daggerfall and hand in Emperor's Courier to Mynisera.
5. You can then speak with Mynisera again immediately to continue with next quest.

I just tested above steps using your save and was able to hand in everything OK. I hope that helps!

**Comment by Ajanddino** [comment]
This is like my third time going through the story and I can not belive I
forgot about this thank you and sorry to have wasted your time.
