### ISSUE TITLE
Quests fail to locate building for Place.

### ISSUE THREAD

**Issue by JorisVanEijden** [Interkarma/daggerfall-unity#1477]
**Describe the bug**
Quests fail to locate building for Place.

The quest system requires every Place used in a quest to have at least one item spawn marker AND at least one npc spawn marker. (`Questing.Place.ValidateQuestMarkers()`)
Even though most quests use a Place for only one of these.

This leads to so many buildings being disqualified that some quests are unable to generate their Places. (https://forums.dfworkshop.net/viewtopic.php?f=25&t=1098&start=30#p29581)

**To Reproduce**
1. go to Daggerfal, Sentinel, Wayrest, Wrothgaria, or Urvaius
2. in console: `startquest O0B00Y11` (or another quest with a Place `local house1`)

**Expected behavior**
A building is found and used for that Place.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.10.5

**Additional context**
I can see a couple of ways to solve this:
1. Parse the quest, see what the Place will be used for and require only that marker type.
2. Add many more item and npc spawn markers to buildings.
3. Change the affected quests to use more common building types.

The 1st option is the most elegant but requires some code change I'd like to get the go-ahead on before working on it.

**Comment by JayH2971** [comment]
Without opining on any particular fix in this case, just wanted to say you're doing tremendous work Joris. Thanks for what you've done so far.

**Comment by Interkarma** [comment]
I'd like to investigate this one a bit more please before deciding on a solution. I'm not sure this is related to marker validation. I will add to this once I've had a chance to look into it further.

**Comment by Interkarma** [comment]
The issue here is not just marker validation, and I don't want to go down the rabbit hole of trying to decide if a quest will only use an item or quest marker during pre-compile. Considering quests can branch out in any number of ways, that just doesn't seem like a good approach. But I think there's a case for looking into this further.

For example, it's likely that in the original design document, "House1" was a house type known to have an item marker only. There's no point even doing pre-parsing if we already know "House1" is only intended to stash items. Validation only needs to check for an item marker for "House1" types. We could use API to collate information about which building types have which markers.

For, the shortest path to happiness is to follow the same pattern as selecting a remote location and provide a fallback to AnyHouse. Not sure why I didn't do this when I implemented building fallback for remote locations some time back.

**Comment by Interkarma** [comment]
This issue should now be resolved by https://github.com/Interkarma/daggerfall-unity/commit/f754202e45dc1485db87b318ede3776e3fa763dc

**Comment by Interkarma** [comment]
Actually going to reopen this one now to chase down the issue around marker validation a bit further. There's also a marker issue I'd like to look at during the same pass for below.

https://forums.dfworkshop.net/viewtopic.php?f=25&t=1098&start=20#p24614

**Comment by Interkarma** [comment]
OK, this one should be completely resolved by https://github.com/Interkarma/daggerfall-unity/commit/3fda78a76da2adbb6c36090556e8f71bd34a9373

Between that and the fallback logic, there should be little to no issues finding a suitable location to host quests now. The exception is when a firm building type is required (e.g. Palace) and one cannot be found in the region.
