### ISSUE TITLE
Forward momentum not retained on sprinting jumps

### ISSUE THREAD

**Issue by drakovyrn** [Interkarma/daggerfall-unity#1588]
Jumping forward while walking retains the same speed while doing so. However, jumping forward while sprinting does not.

The first sprinting jump is at the same speed as sprinting, but every consecutive jump afterward is done at walking speed.

Easier to notice with a character with a high jumping skill. Very noticeable if set_runspeed = 30.

Current pattern of jumps:
Walking: Short, Short, Short, Short, etc.
Running: Long, Short, Short, Short, etc.

Expected pattern of Jumps:
Walking: Short, Short, Short, Short, etc.
Running: Long, Long, Long, Long, etc.

OS: Windows 7
DFUnity Version: 0.10.10

Not save-dependent, but here's a decently running skilled character in the Wayrest castle courtyard with plenty of space to run around and test this behavior:

[SAVE1.zip](https://github.com/Interkarma/daggerfall-unity/files/3777178/SAVE1.zip)

**Comment by petchema** [comment]
How does it work in classic?
Does it help with "platforming" cases, like in Mantellan Crux?

**Comment by drakovyrn** [comment]
It works as the "expected" pattern.

Specifically, the character will long jump whenever the sprint button is held.

It does help in platforming cases, but also getting away from enemies. Currently, the jump only long jumps the first time, and then goes back to short jumps.

**Comment by bansheexyz** [comment]
The OP is talking about "Bunnyhopping". It's this ultra-unrealistic mechanic that makes spamjumping just as fast as sprinting. So everyone starts bunnyhopping exclusively to move because it makes you way harder to hit and there's no downside. It's also disorienting and unpleasant to watch. Imagine every let's play of an first-person game looking like this: https://www.youtube.com/watch?v=Lw5lKtvpv4g

I used to play a lot of HL1 deathmatch, so I know what it is. The mechanic died with HL2 and Counter-Strike, but people still have some kind of misguided reverence towards it.

**Comment by drakovyrn** [comment]
You're comment is entirely misguided and unnecessary. It is already
possible to bunny hop in original Daggerfall and in Daggerfall Unity.

I am not asking to implement bunny-hopping (which is already implemented),
I'm asking to replicate vanilla behavior regarding forward speed while
holding sprint while jumping. So your point is moot and unnecessary here.

**Comment by drakovyrn** [comment]
Needlessly angry point still irrelevant, as bhopping is already
implemented, and what I'm asking is for the behavior to work consistently,
not even just compared to vanilla, but compared to itself, as forward
momentum is already kept for walking speed, it only doesn't do so for
sprinting.

I'm not a coder, but I imagine the fault is that the jump mechanic isn't
checking that the user is holding the sprint function when jumping more
than once.

In vanilla, the user can hold the jump button, and switch between walking
speed jumps and running speed jumps only contingent on the status of the
sprint function.

That's all I'm asking -- it's a bug report, not a feature request, and has
nothing to do with the nature of bhopping in video games.

**Comment by Jeoshua** [comment]
I can confirm. Steps for replication are straightforward: hold forward, jump, and run. First jump is at run speed. Subsequent jumps are at walk speed.

And this isn't just an exploit to be avoided. This is a single player game focused on recreation of expected behavior. To claim its an exploit is like trying to remake Quake 1 without Rocket Jumps.

**Comment by bansheexyz** [comment]
> This is a single player game focused on recreation of expected behavior.

Expected by who and which things? Physics and jump mechanics were broken in general. The gravity was floaty like being on the moon, you barely lifted off the ground, and you couldn't look around while jumping. There is no reason for any of this to be preserved.

PS. Rocket jumping broke Quake 1's level designs. Romero didn't know it could be done until after release when they saw videos of people circumventing puzzles and elevators. Not that DF has anything like this.

**Comment by petchema** [comment]
Gave a try at fixing this issue: https://github.com/Interkarma/daggerfall-unity/compare/master...petchema:keep-running

You can only switch running on/off when touching ground; But while hopping, switch seem to only happen on 2nd touch down, I haven't found why

**Comment by petchema** [comment]
Okay, effective speed is delayed one hop because it's transmitted to movement by
`moveDirection = myTransform.TransformDirection(moveDirection) * playerMotor.Speed;`
in FrictionMotor.GroundedMovement(), which is called right after grounded condition has been detected.
So first hop sets speed, second hop changes movement to match speed. Mmh

**Comment by petchema** [comment]
Should be fixed in 0.10.19
