### ISSUE TITLE
Unable to load classic save whith character equipped with a CastWhenHeld magic item

### ISSUE THREAD

**Issue by df-ferital** [Interkarma/daggerfall-unity#1849]
**Describe the bug**
Since I implemented CastWhenHeld item condition lowering in PR #1827, I'm unable to load a classic save with a character equipped with such kind of magic item. 

**To Reproduce**
1. Load the provided classic save.
2. The item will broke immediately in an infinite loop.

**Expected behavior**
The game should load and the item isn't supposed to break since such items condition lowering should be done on equip only.

As I'm not quite familiar with how the current system is implemented, it might be better if you check what's happening there, @Interkarma.

[SAVE2.zip](https://github.com/Interkarma/daggerfall-unity/files/4863670/SAVE2.zip)

**Comment by Interkarma** [comment]
Cast When Held items also lose durability over time, not just on equip. I'll look at save provided when I can and see what's happening.

**Comment by Interkarma** [comment]
The issue here is unrelated to CastWhenHeld or durability loss. It's caused by an exception in ImportMembershipData() while trying to import oldMembershipRecords. The data being read from oldMembershipRecords cannot be cast to a GuildMembershipRecord. Seems to have been introduced after #1845 as I'm able to load that save in prior versions.

I've added some exception handling to ImportMembershipData() and this imports now. The corrupt/bad membership data is discarded instead of crashing the game.

**Comment by df-ferital** [comment]
Ah thanks, sorry I should have tried to investigate the issue further, but didn't find the time to do it. And you're right, CastWhenHeld items also lower their condition over time, my mistake.
