### ISSUE TITLE
Got no response from Aubk-I when completing Mynisera's Letters main quest

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1902]
**Describe the bug**
After recovering the burnt letters from Castle Necromoghan, clicking on Aubk-I does apparently nothing. The quest is marked completed though.

**To Reproduce**
1. Load gamesave below
2. Click on Aubk-I
3. Get no reply, but quest is finished

**Expected behavior**
Aubk-I comment on letters' content
https://en.uesp.net/wiki/Daggerfall:Mynisera%27s_Letters#Reward

**Desktop (please complete the following information):**
 - OS: Linux
 - Version master (61c8c05)

**Additional context**
Error in log:
[S0000013] Error in quest follows. Terminating quest runtime. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Specified cast is not valid. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[SAVE729.zip](https://github.com/Interkarma/daggerfall-unity/files/5112199/SAVE729.zip)

**Comment by Interkarma** [comment]
> P.S.: Fixed by rebuilding addressables

Glad you sorted it. :)

If using Play Mode Script > Use Existing Build, then Addressables will need to be rebuilt on developer side anytime text is updated.

If using Play Mode Script > Use Asset Database, then it should always pull from assets directly rather than from built addressables. I recall you had some trouble with that play mode script before though. Not sure if that's a condition unique to the Linux editor or not.

**Comment by petchema** [comment]
Probably because I barely ever use the editor UI for running the game.
Instead, I used it as a command-line compiler, scripting a build (based on the Makefile solution that was once published in the forums) and a deployment.
But I don't know if addressables can be rebuilt that way...
