### ISSUE TITLE
Unity build error System.Windows.Forms.dll makes the game unplayable outside the editor

### ISSUE THREAD

**Issue by AleZaTar** [Interkarma/daggerfall-unity#1954]
As soon as Unity finishes creating a build the console gives me an alert message about System.Windows.Forms.dll is not supported on StandaloneWindows64 platform. As a result, various bugs and freezes happened during the gameplay. As an example, there is a screenshot of the startup scene that shows me nothing(or it just freezes). Earlier it froze in the custom class creator screen. Also, I noticed that the names for factions and skills are not loaded (they give some error messages instead).

**To Reproduce**
1. Open Unity with Daggerfall project
2. Do not change anything
3. Create a build with default options in a separate folder
4. See in the Unity console the alert message (System.Windows.Forms.dll)
5. Launch the game
6. Errors may vary in the game and eventually will lead to freeze

**Expected behavior**
The full alert message is like this: 
System.Windows.Forms.dll assembly is referenced by user code, but is not supported on StandaloneWindows64 platform. Various failures might follow.
UnitiyEngine.GUIUtility:ProcessEvent(int32, intPtr)

**Screenshots**
https://i.imgur.com/qXUZhqY.png
https://i.imgur.com/FahWll8.png

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate 64bit
 - DFU Version 0.10.27
 - Unity version 2019.4.12f1, 2019.4.10f1

**Additional context**
I am new here and I don't know that much so feel free to correct me and ask me additional questions. I hope I provided you enough info to deal with the bug.

**Comment by Interkarma** [comment]
Hi, this seems like an issue with Unity on user side rather than with DFU. Nothing like this is experienced when managing or creating builds here.

You'll need to be using Unity 2019.4.10f1 (specifically this version) with a clean clone of the source. You might also need to rebuild your addressable content prior to creating platform build. This is done from Window > Asset Management > Addressables > Groups then selecting Build > New Build > Default Build Script. See link below for more info on addressables.

https://docs.unity3d.com/Packages/com.unity.addressables@1.3/manual/AddressableAssetsDevelopmentCycle.html

Hopefully that's of some help. Please feel free to open a topic on forums if more general help needed with build process.
