### ISSUE TITLE
Add shop info to their automap nameplates

### ISSUE THREAD

**Issue by XJDHDR** [Interkarma/daggerfall-unity#2001]
On DFU's roadmap, it says that all game features have now been implemented. However, there is one feature in vanilla Daggerfall that has not been implemented in DFU: The ability to write on the Automap. Originally, the player could edit the text that was attached to a building's door as well as add their own text to the map. 

In DFU, neither of these things are possible. Are there any plans to add this feature or is it's absence intended?

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Version 0.11.0

**Comment by Interkarma** [comment]
Absence is intended. Classic's exterior automap will also tag buildings with useless "residence" labels that clutter up the map, and leave behind random building names associated with quests that have long been completed. Sometimes residences will have multiple names based on prior quests that have been assigned to same building. Nameplates will also overlap making it difficult to read either name. The ability to edit nameplates in classic feels more like a response to manage the mess rather than adding anything of real value.

In DFU, we've instead taken great pains to avoid clutter in the first place. There are no more "residence" labels or leftover random names from completed quests. Nameplates will never overlap and tooltips help disambiguate. The map is more readable - it can even be zoomed, rotated, and panned by mouse alone. The DFU automap is intended to be clean and self-managing and only convey useful information. I believe at this stage that adding/editing nameplates would only be a curiosity that few people would use. Not many users seem to request or care about this feature, I can't even recall the last time it came up.

With that said, I'm not opposed to custom player text on automap as a feature. I just believe we're already doing something better in refining map behaviour.

Feedback is most welcome. Maybe @Nystul-the-Magician would like to weigh in - the automaps are his creations and I'd value his input.

**Comment by XJDHDR** [comment]
The main reason I used the "write on map" feature was to write down the quality of stores in a settlement and what type of stores they were, if the name didn't make it obvious. As great as the new map is, I don't see anything there that replaces the above. 

Instead, since switching to DFU, I've had to write this info on pieces of paper. This is more cumbersome and the only part of DFU that I feel is a downgrade compared to the original.

**Comment by Interkarma** [comment]
Cheers, I appreciate the feedback. :)

Well, I'm happy to add the ability to edit building nameplates with custom text to begin with. That will slot in neatly with how building discovery serialization and nameplates work now.

Adding custom nameplates anywhere would be more work and need some additional serialization and some automap refactoring. What value do you see in adding nameplates anywhere - i.e. not associated with a building?

**Comment by Nystul-the-Magician** [comment]
This is a nice compromise I guess.
An implementation of custom nameplates would be not that tricky to do but will require the location automap to store that info somewhere. The nice thing with just using discovery serialization is that no additional info needs to be stored by the automap class itself.
Whoever wants to extend the automap with nameplates - feel free to do so - I could point you to the places in code where I think it would be best to put it in ;)

**Comment by XJDHDR** [comment]
I would say only being able to edit the existing nameplates would be all I need to replace what I did in the original game. Or even just the ability to append text without editing what's already there.

Can't speak for everyone but I don't have any need to add nameplaces anywhere. Mainly proposed it just because classic Daggerfall had it.

**Comment by Nystul-the-Magician** [comment]
I once though about a pop up window when hovering over nameplates that showing shop opening times and quality level, but I never came to implement this. This would be a nice mod, though.

**Comment by ajrb** [comment]
Would saving as a name override in discovery data be okay for this? It would mean no new save data is required and the system is already there.

**Comment by Interkarma** [comment]
>Would saving as a name override in discovery data be okay for this? It would mean no new save data is required and the system is already there.

Yep, that was my suggestion above for same reasoning. Great minds think alike. :) I'd maybe add a new field in discovery data for custom names, then a popup box when clicking on nameplates to edit text like renaming characters or spells. If player submits a blank name, it will clear the custom name.

Is this a feature you wanted to take on? I'm happy for you to implement if the idea has grabbed you.

**Comment by ajrb** [comment]
> Is this a feature you wanted to take on? I'm happy for you to implement if the idea has grabbed you.
Not really, unless you want me to.. I was just trying to give a (possibly) helpful suggestion.

**Comment by Interkarma** [comment]
Resolved by 1f56eef.
