### ISSUE TITLE
Load assets from both the install StreamingAssets directory and a StreamingAssets directory in a userspace directory

### ISSUE THREAD

**Issue by Star-X555** [Interkarma/daggerfall-unity#2027]
This isn't so much an issue on Windows, but on Linux, installing Daggerfall Unity as a package (e.g. Arch Linux with AUR support) means that modifying what mods you use requires root access.  As most of the GUI means of doing so are pretty crappy, it forces command line usage to make any modifications to the StreamingAssets directory if it's installed in something like /usr/bin.

To fix this, add support for loading StreamingAssets from user directories, e.g. ~/.local/share/daggerfall-unity/StreamingAssets.

**Comment by Interkarma** [comment]
Hey there! :) The location returned by Application.streamingAssetsPath is exposed through Unity runtime and varies by platform. It isn't a changeable path and will always reside inside of application path.

The data inside of StreamingAssets will change from build to build and might contain bug fixes for core data (e.g. quests and faction data). Decoupling this path from application would also require you to keep StreamingAssets maintained for core files elsewhere. That's not a design I wish to support.

The only supported install method for Daggerfall Unity is to extract zip file to an easily accessible location. On Linux, this might be your home directory or documents folder. Installing as a package isn't a supported install method.

**Comment by noabody** [comment]
I do my own thing, which includes building from source code on Arch like Manjaro.  Instead of `opt` I got used to `usr/share`, probably from Debian.  Anyway, this is the script I use.  

To enable *mods*, I use a global install that then mirrors >7Mb of files (main script and StreamingAssets) into the local configuration, and sym-links all remaining folders to simulate a local install in user-space.  This script employs rsync in order to update the main script based on checksum.  The --ignore-existing parameter won't make changes to existing files to ensure *mods* are not replaced when the program updates.  If significant changes are made to `StreamingAssets` that would require the files be updated, the folders would need to be manually removed.

```
#!/bin/bash
gmcfg="$HOME/.config/unity3d/Daggerfall Workshop/Daggerfall Unity"
glnch="DaggerfallUnity.x86_64"
i_syms=()

test -d "$gmcfg/DaggerfallUnity_Data" || mkdir -p "$gmcfg/DaggerfallUnity_Data"
readarray -t i_syms < <(find /usr/share/dfunity -mindepth 1 -maxdepth 2 ! \( -iname '*dfunity.sh' -o -iname "*$glnch" -o -ipath '*StreamingAssets*' -o -ipath '*DaggerfallUnity_Data' \) -printf '%P\n')
for i in ${!i_syms[@]}; do
  test -h "$gmcfg/${i_syms[$i]}" || ln -sf "/usr/share/dfunity/${i_syms[$i]}" "$gmcfg/${i_syms[$i]}"
done
unset i_syms
rsync -c "/usr/share/dfunity/$glnch" "$gmcfg"
rsync -rc --ignore-existing /usr/share/dfunity/DaggerfallUnity_Data/StreamingAssets "$gmcfg/DaggerfallUnity_Data"
(cd "$gmcfg" && "$gmcfg/$glnch")
```
