### ISSUE TITLE
Missing  graveyards

### ISSUE THREAD

**Issue by d3vv** [Interkarma/daggerfall-unity#2080]
For a example, into original dos-game we have a graveyard "The Copperston Crypts" of Daggerfall country:

https://elderscrolls.fandom.com/wiki/The_Copperston_Crypts

As I see, that's missing from the Daggerfall Unity..

**Comment by petchema** [comment]
No, they're "common cemeteries" and "forgotten cemeteries", the latter not showing up on map until you discovered them, like standard dungeons.

https://en.uesp.net/wiki/Daggerfall:Cemetery

To find the Copperston Crypts:
- be sure to be in the Daggerfall Region;
- open the console and type "map_reveallocations"
- open the travel map, you can now go to The Copperston Crypts

**Comment by d3vv** [comment]
But into original dos-game it is not "forgotten".. I can always go to there from start with travel map as well

**Comment by petchema** [comment]
Okay, this is clearer now. Indeed it seems what cemeteries are known at the start of the game doesn't seem to match exactly between Daggerfall and Daggerfall Unity:
![classic daggerfall](https://user-images.githubusercontent.com/1211431/115109683-8c60a280-9f77-11eb-9210-ad1fa61f43e4.jpg)
![daggerfall unity](https://user-images.githubusercontent.com/1211431/115109686-91bded00-9f77-11eb-9579-3697cd0184fb.jpg)

**Comment by Interkarma** [comment]
These graveyards aren't missing as Pango described. Only the initial discovery state of these locations isn't identical between DFU and classic.

The way classic determines initial discovery state for small graveyards is unknown and likely random at some point in game startup with an undefined seed. This won't be possible to match perfectly without access to original source.

It's of little importance in any case. These dungeons aren't used for anything more than flavour and to provide an initial set of small dungeons to explore. Effectively both games provide the same functionality and even have a huge overlap in initial graveyards. It doesn't really matter if some of these graveyards aren't visible initially in DFU or vice versa.

This isn't something that I plan to spend time on. Even one of our best reverse engineers wasn't able to match this perfectly, so likely it's an emergent random result rather than a defined one. I'll leave it open for now in case someone else wants to pick up later and have a crack at it.

**Comment by d3vv** [comment]
@Interkarma 

1. Does it possible to get acquainted with the existing developments of your "best reverse engineers"?

2. Would you like to match your approaches to the XLEngine's approaches?

https://github.com/Mindwerks/XLEngine

If the author of DaggerXL (a part of this engine) relied solely on the analysis of reverse research..

https://daggerxl.wordpress.com/

**Comment by d3vv** [comment]
https://github.com/luciusDXL/XL-Engine

**Comment by petchema** [comment]
Well, DaggerXL used a lot of Interkarma's reverse engineering work...
https://forums.dfworkshop.net/viewtopic.php?p=50878#p50878

**Comment by Interkarma** [comment]
You have things backwards here. DaggerXL is roughly up to where DFU was in its first few months, with very few gameplay features implemented. Much of what it did implement was given a leg-up thanks to an active reverse engineering community beforehand.

Again, I'm not trying to diminish Lucius' work. This kind of thing is notoriously difficult and life-consuming. Lucius had every right to start and stop as his life required. Lucius was also working by himself, while DFU has been lucky enough to have over 40 developers working on it throughout its lifetime.

To bring things back on topic: Initial graveyard discovery state in classic and DFU are just two different random sets that provide the same gameplay purpose. There's no gameplay need to match this perfectly, and it's not something I attribute any importance or priority to. I'll leave this open in case someone wants to take a look at later, and close it if it doesn't gain any traction.

**Comment by KABoissonneault** [comment]
I happened to be reverse engineering the data found in dungeon locations as they're parsed from MAPS.BSA, since DaggerfallConnect still has many "unknown values".
I compiled all "unknown values" for the fields (and subfields) of LocationDungeon in this CSV, after stripping values that are always 0 for all dungeon locations.

[dungeons.csv](https://github.com/Interkarma/daggerfall-unity/files/6361856/dungeons.csv)

Since you had me curious, I also compiled the list of revealed dungeons in the Daggerfall region for classic TES2 [here](https://github.com/Interkarma/daggerfall-unity/files/6361967/cemeteries.txt). I could have missed one or two.

If you open the CSV file in Excel or LibreOffice Calc and use AutoFilter, you can then filter to only show the rows with the Region Daggerfall and the Type "Cemetery". You should be left with 72 rows.

I've managed to identify some of the unknown values, but this CSV still contains 3 columns I haven't identified: "Flags" (the values in the file are in hexa), "A", and "B".

With this data, I cannot identify any pattern that could identify what locations are automatically revealed by default. 
It's not the "Index" column (ex: revealing the first half of the 72 cemeteries), since The Gaerford Tombs are at the bottom of the list and they still start revealed.
It's not the "Flags", since all cemeteries have 0x10000 in Flags, including the "forgotten" ones. 
"A" is pretty much a random byte across all dungeons in the game, might have been used as a seed for random elements. 
"B" usually has a value between 0 and 9, and for the Daggerfall cemeteries it's 0 or 1. But locations with 0 can be either revealed or unrevealed, same for 1, so clearly that's not it.

Maybe someone else might find a correlation I missed, but beyond that, I'm gonna go with IK and assume it's random (could be based on the "A" values I posted, but we still don't know the formula). I assume it's a coinflip, since about half the cemeteries are revealed in the Daggerfall region.

Strange mechanic, regardless.

**Comment by Interkarma** [comment]
Thank you for taking a look @KABoissonneault 👍

**Comment by ajrb** [comment]
Sorry I am late to this discussion, not sure I am correct or not but I thought this was being determined from the file MAPS.BSA. MapsFile.ReadMapTable() reads a 32 bit bitfield and parses into MapTable.Discovered a boolean value that I thought determined if a location appears already discovered at the start of the game.

That's certainly the bool field that the world data overrides use for this, maybe I should check if that actually works how I think?

**Comment by Interkarma** [comment]
@ajrb The Discovered flag doesn't account for starting graveyard state. It's inconsistent with locations. See Allofich's comments in #544.

**Comment by KABoissonneault** [comment]
According to the reverse engineering work in UESP: https://en.uesp.net/wiki/Daggerfall_Mod:MAPS.BSA#Location_GPS_Record_.28MapTable.29

The Map Table record has another bit called "Hidden" that DFU does not parse yet (ie: the bit is entirely ignored). I'll take a look at this later and see if that bit is set for the "forgotten graveyards". I'll take a crack at some of the "unknown values" from the exterior data too

Off-topic, but the structure described on UESP has Longitude and Latitude inverted compared to `MapsFile.ReadMapTable` - I wonder if anyone has any insight on that

**Comment by KABoissonneault** [comment]
I generated a table similar to the dungeon interior one I linked earlier, except it's for the map table of the dungeon exterior.

I will link the file here for those curious.
[dungeons_exterior.csv](https://github.com/Interkarma/daggerfall-unity/files/6448819/dungeons_exterior.csv)

Unfortunately, the Hidden bit is false for every dungeon location, so it could not be what cause some graveyards to not be revealed. And as documented in DFU code, the Discovered bit correlates but does not perfectly match with what graveyards are revealed in classic TES2.

**Comment by Interkarma** [comment]
Both classic and DFU's starting states of graveyards are random, only the random selection is different. It's functionally the same outcome however to give player a number of small dungeons to explore at start of game. The variable graveyard discovery state has no impact on gameplay.
