### ISSUE TITLE
Rumor mismatch between DFU and classic

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2136]
There seems to be a mismatch between DFU and classic in terms of what shows up when you ask for "Any News?".

For example, we ran some tests in classic with two characters, asking for 15 rumors.

Here were the results
```
Fresh PC : 

Generic : 0
Region conditions : 7 (ex: regime changes, alliances, etc...)
Tutorial Quest: 3
Main Quest : 5 (ex: Don't walk the Daggerfall streets at night)

PC with 2 quests active and other recently done quests : 

Generic : 0
Main Quest : 1
Post-quest : 4
Current quests : 10
```

Meanwhile, in DFU, regardless of context, alliance changes seem to pop up more often than anything else.
I compared the RUMOR.DAT from both classic playthroughs above, and they definitely didn't generate as many rumors as one would find in ConversationData.txt in the equivalent DFU playthrough.

So I suspect we have two issues:
1) we generate conditions at a higher frequency than classic
2) we lack a priority for quest rumors

Does anyone have any info on the investigations / resources that were used for the implementation in TalkManager and PlayerEntity?

**Comment by Interkarma** [comment]
This feature was implemented by a one-time contributor and just hangs off the conversation rumour mill with some basic filtering. If someone wants to perform the reverse engineering or refinement, we can incorporate that. Otherwise, I'm happy for it to remain in a "best effort" state. It's not like this is a critical gameplay feature or particularly useful in classic either. It's just a dash of flavour.

**Comment by KABoissonneault** [comment]
Alright, then I'll give it a shot this month, before the code freeze

**Comment by Interkarma** [comment]
That's OK, provided changes aren't too broad. My goal with notifying of upcoming freeze was for contributors to wrap up anything they already had in progress - not provoke a rush to fit in as many changes as possible before cutoff. :) I still want long-term stable code to undergo relatively few changes before the freeze starts next month. A large part of the final push to 1.0 is my confidence in existing systems.

So minor refinements to the notice boards specifically are fine, but a refactoring of the entire rumour system might not be depending on the scale you have in mind. Just so you know before committing too much time into this.

**Comment by Interkarma** [comment]
Oh, I just realised you were speaking to the rumour mill in general, not just bulletin board notices. Not sure how I got that idea. Please disregard my previous comment about bulletin boards.

The people most involved with talk system are @Nystul-the-Magician and @df-ferital. Ferital has reverse engineered several elements from classic talk systems and reimplemented in DFU to match classic. But I don't believe anyone has made any reverse engineering attempts to match ambient rumour type and frequency with classic. That might be something Ferital or Nystul have notes on however.

I'm actually very hesitant to refactor any talk systems at all at this point, unless it's a very directed change from someone already involved with the systems. I'd prefer not to open this up to modding without some clear benefit and purpose to it, and don't want to risk downstream issues with quests etc. this close to freeze.

**Comment by df-ferital** [comment]
I have reversed engineered the entire classic rumors system, as Allofich did a few years ago.

It appears that there is a mismatch between DFU and classic but DFU behavior is the correct one. Classic mechanics are bugged because each time a quest is started, a `lseek` call is made which sets the RUMORS.DAT file pointer to the beginning of the file. All quest rumors are then added to the file buffer, which has the effect of litteraly erasing all previous rumors, regardless of the fact that they may still be active. This explains why quest rumors are immediately available in classic, however this is definitely not the correct behavior.

**Comment by Interkarma** [comment]
Awesome, thank you Ferital! I'm sorry for not remembering this.

**Comment by df-ferital** [comment]
No problem, actually I didn't remember this well either and what I said above is not entirely exact. Rumors are erased not because of quest startup, but because classic rumor mill does not regenerate rumors often enough. Here are the comments made by Allofich regarding this issue:
`In classic this version of the function is called within the conditional for the above, when both
(i + lastGameMinutes) % 10080) == 0 and (i + lastGameMinutes) % 54720) == 0) are true, or every 266 days.
I'm pretty sure it was supposed to be every 38 days.`

**Comment by KABoissonneault** [comment]
What do you think of a compromise where I add a setting ex: "Prioritize quest rumors", which ensures every new quest rumor is shown at least once before moving to the rest of the rumor mill?

Discussing with some people, I think some users like quest rumors, and even if it was by accident, they were more prominent in the classic game. I think an opt-in setting with a minimal change in behavior would be a good compromise for this point in development.

**Comment by Interkarma** [comment]
Sure thing, as long as it doesn't impact the current rumour mill function I'm happy to take a look at the proposed changes. :)

**Comment by KABoissonneault** [comment]
If #2140 makes it, I think mods will be able to replace the rumor system entirely, so differences in "how it should work" could be resolved that way. I'll consider this issue "not an issue" after that

**Comment by Interkarma** [comment]
@KABoissonneault Are you happy for this one to be closed with the recent changes to rumour weighting?

**Comment by KABoissonneault** [comment]
Yup. I forget you push new changes without going through a PR, so I didn't event notice :P Haven't had time to test it yet but I'm confident this will help
