### ISSUE TITLE
Invalid scale in TextureFile

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2159]
I was going through the Texture code, and found this:
https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/API/TextureFile.cs#L351

```
        public DFSize GetScale(int record)
        {
            // Validate
            if (record < 0 || record >= header.RecordCount || records == null)
                return new DFSize(0, 0);

            return new DFSize(records[record].ScaleX, records[record].ScaleX);
        }
```
Pretty sure that return statement should be `return new DFSize(records[record].ScaleX, records[record].ScaleY);`

While we're at it, can anyone explain to me what the scale is for? I'm working on allowing DaggerfallMobileUnit to use textures outside of the 512 classic textures, and I want to make sure I get this part right. Given an arbitrary PNG that doesn't have an equivalent Arena2 texture, what should the scale values be?

**Comment by Interkarma** [comment]
This does look like a typo but could have been intentional at the time. This method dates back to pre-2009 and I can't recall where things were at in the data understanding. In practice ScaleX and ScaleY are always the same number so it shouldn't be an issue either way. Happy for this to be changed so it's clearer to read.

Offset and Scale are mainly used to position static flats in world. Without these, static NPCs in castles won't have their feet aligned to ground or roots hanging from ceilings won't be attached, for a couple of examples.

For mobile enemies, you won't have to worry about this provided all images of the enemy are proportional to each other. For mobs, classic mainly uses this to correct for angles that are different sizes. See the tiger as an example, the front-facing texture is 45x80 and the back-facing texture is 27x42. This saves on memory for an angle the player rarely sees up close and the scale will make both billboards the same physical size in world. Proportional mobs all have a scale of 0 and this will also be OK for arbitrary PNGs that are drawn properly,
