### ISSUE TITLE
Journal entries expand macros on every access

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2174]
**Describe the bug**
A journal entry's macros will be expanded every time the journal is accessed or changes mode. This can lead to some inconsistencies, in cases where a macro would expand differently at a different time or location.

**To Reproduce**
1. Get a quest entry with a message like `_location_ is %di from here.`  (ex: "Cave of Example is north-west of here.")
2. Move at another position relative to the target location 
3. Open "active quests" journal
4. See inconsistency (ex: "Cave of Example is west of here.")

**Expected behavior**
An entry should be expanded once - the moment it is written - and remain the same until it disappears.

**Additional context**
Someone hit this issue while writing a custom quest, which required locating a location inside town. It's pretty easy when your journal magically updates on the fly. I'm not sure if any classic quest relies on this, but I hope not?

**Comment by Interkarma** [comment]
This dynamic text capability is used by QoL option to count down a quest timer in journal rather than showing a fixed value. And overall most macros will expand the same each time in journal due to their source inputs being fixed in quest data. There's only going to a small number of macros like %di where this is an issue for the journal specifically.

I do accept the issue and will see what I can do to help with this problem without fully restructuring how journal handle text.

I have some other plans to work on journal to add smooth scrolling (a QoL feature I promised some time ago) and will look into this around the same time.

**Comment by df-ferital** [comment]
I don't agree with this being an issue. In original quests, %di appears only on dialogue messages and more generally, it is not supposed and should not be used elsewhere.

**Comment by KABoissonneault** [comment]
Yeah, I suppose it's more of a modding support issue. I think it's worth considering if there's a way to fix it without impacting other features.
If classic really relies only on macros that have a fixed result, then certainly caching the result once and never evaluating it again shouldn't have an impact, right?
Seems like it's only there for an optional DFU setting. 
Maybe we can replace most macros by text tokens once the entry is written, but keep certain parts (like the quest timer) still requiring to be evaluated.

**Comment by df-ferital** [comment]
I understand your point, my concern was more focused on the macro system rather than the journal, and I think it would be quite hard to do something there without breaking stuff. However, @Interkarma may have some idea on how to correct this for quest journal entries.

**Comment by Interkarma** [comment]
I think it's perfectly acceptable that not all macros are expected to useable in all situations. You might notice their complete name is "context macro". I called them that because they're quite literally intended to expand within a specific context. If a macro isn't intended for use in the journal context then maybe it just shouldn't be used that way. Sometimes the correct answer is simply "then don't do that".

But I do want to help and will take a look to see I can mitigate this case in the journal. To set expectations, I won't be making any substantial changes to either journal or macro expansion. And if I can't see a trivial way to mitigate this macro in journal, then no changes will be made.

**Comment by Interkarma** [comment]
I've been thinking about this one while building out more of localization. I've come to the conclusion this would be very difficult to refactor cleanly. Further, the ability for macros to expand each time is rather useful when applying or removing translations, and when testing localized strings.

I can see the issue when a macro intended for conversations (%di) is used elsewhere (journal). But that's really an expected problem with using a macro out of context. I favour keeping the flexible expand-as-needed context-sensitive design currently in place. Perhaps some other custom macro could be added to resolve the %di problem in journal text.
