### ISSUE TITLE
Cosmetic issue with item names in item maker

### ISSUE THREAD

**Issue by bernsamr** [Interkarma/daggerfall-unity#2181]
If you give an item of some material (Iron, Steel, ..., Daedric) a custom name in item maker they are not called like you name them. Instead they are called "%material %custom_name". This gives your items funny names like i.e. "Silver John Doe's Axe".

**Comment by Interkarma** [comment]
This is intentional and matches classic (screenshot below from classic).

![fall_003](https://user-images.githubusercontent.com/10426244/126086399-a75537dd-12bc-425b-8093-927b38b2af4f.png)

No plans to change right now. Perhaps it could be be added later as an optional QoL setting or by a mod if possible.
