### ISSUE TITLE
Quest fix needed: A0C00Y16, Missing Person Case

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2190]
I'm aware I'm "the quest person," but there are times when a job is really, really beyond me. Anyone is free to pick this up and try to fix it. The sheer number of variables and paths through this quest makes it gigantic to debug and repair properly.

I'm not going to give a thorough explanation of what's broken in the quest (if I could, I'd fix it and be done with it), but a few of the problems are NPCs who should appear in buildings where they don't, quest topics that should be made available but don't, and paths that depend on certain actions to happen but don't. Whether people choose to collaborate or work on it separately is up to them.

This issue is for workflow's sake, so we don't forget about it by the time 1.0 comes around.

**Comment by mundifex** [comment]
Once #2194 #2197 and #2198 are in place, I think you will find that A0C00Y16 functions in a much better fashion, at least comparing to vanilla Daggerfall. #2199 polishes the presentation a bit.

Question for @df-ferital: does #2198 correct the issue where reading the log entry for the quest automatically adds _missingperson_ as a dialog link? I found that, depending on which "path" the quest selects, you can discern whether the missing person actually exists (i.e. path _S.00_) by reading the log entry immediately after the quest begins: if you end up with 4 people entries, the missing person exists and can be found; 3 entries implies the alternate paths where you will never physically locate the missing person (i.e. paths _S.01_, _S.02_, _S.03_).

For reference, quest flow for each path:
- **S.00**: _friend1_ reveals _hidingplace_ which contains _missingperson_ NPC
- **S.01**: _friend2_ refers to _friend4_ who had Smiley murder missing person
- **S.02**: _friend2_ knows missing person got arrested
- **S.03**: _friend1_ refers to _friend3_ who knows that missing person skipped town

As soon as _missingperson_ appears as a Where Is topic, path _S.00_ is ruined by mobile NPCs revealing _hidingplace_. Ideally, I think we either want _missingperson_ to never show up as a Where Is topic (which hopefully #2198  facilitates) or only after _friend1_ has revealed _hidingplace_ which we could do with an additional `add dialog for person` statement in the quest file (something I did not add in #2199 since I wanted to discuss first).

**Comment by df-ferital** [comment]
Hi @mundifex, #2198 does indeed correct the log issue where `missingperson` is added to "Where Is" topics when you read the log entry. However, there is still an issue in DFU where simply asking any `friend` about `missingperson` will show `missingperson` as a "Where Is" topic, which also ruins quest path `S.00`. The only solution I got in my own quest patch (which is very similar to yours) is to add `dialog link for person _missingperson_` to each of the 8 states activating when you speak to a `friend`.

However, this solution is not the classic way of doing this and adds more quest scripting. In fact, what classic does is to display a previously hidden person as a `Where Is` topic only if its place is not also hidden _or_ if it is added through the `add dialog` command. This is why this command is needed for `friend3` and `friend4`, since they are hidden by the (misnamed) `dialog link` command. So I will need to improve my PR a little to handle this properly.

**Comment by Interkarma** [comment]
The biggest problem in this issue looks resolved by #2199. Further fixes will be provided by #2198 and @df-ferital's refinements. I'll close this issue, as further changes are related to a system rather than this quest specifically. This issue will still be linked in the comments history of #2198.

**Comment by JayH2971** [comment]
I haven't heard complaints about this quest in months. Sorry for not closing it myself!
