### ISSUE TITLE
MobileEnemy.CorpseTexture fails on texture archives outside of 0-511

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2230]
With custom enemies, you want custom corpse textures. Right now, if you try to use an archive beyond 511 (ex: `CorpseTexture = EnemyBasics.CorpseTexture(1000, 1)`), there's an error with the texture import down the line, and the corpse billboard won't appear.

I'm looking into it, but if someone more knowledgeable with the texture import system wants to have a look, feel free.

**Comment by Interkarma** [comment]
Just spitballing since you've had no other replies. My feeling is this could happen at a low-level inside TextureFile.cs as archives above 511 don't exist in gamedata files. I'm not sure if texture replacement handles this case or not. Stepping into code in debugger should eventually show where it bounces as the call is passed down from mod through to DFU and eventually down into the basic reader classes.

**Comment by Interkarma** [comment]
Hey KAB! I understand this one was resolved by #2242, so will close now.
