### ISSUE TITLE
Formula: MagicResist never used?

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2236]
As I was overriding SavingThrow, I looked at the implementation, and realized MagicResist or willpower is never used.

I searched the repository, and it seems `FormulaHelper.MagicResist` or willpower is only used in text, never in any gameplay.

The `MagicResist` formula seems to have always been there in the history `FormulaHelper.cs`.

https://github.com/Interkarma/daggerfall-unity/commit/35b8a701ea50555e908014fde8d94af08db3de19#diff-bf9295b9fff018a5e18b5cae16392594eaa14d9b95a0691b5948008233a56e7d

It was taken directly from the UI of the character sheet, so it wasn't used in any gameplay then back then.

The `SavingThrow` formula was introduced here
https://github.com/Interkarma/daggerfall-unity/commit/a661dd197bdc46ae8e6929252eeae9486076146b#diff-c7ed070101c269a9e156a2cf09e1d16a2d1ee863870ca7eb01fc54514b39505fR715
and it seems over the years, only bits were added as needed. It wasn't directly reverse-engineered.

I'm starting to suspect MagicResist was just forgotten from the implementation? 

I'd like a comment from someone more familiar with the history of that code to make sure I'm not missing something, or if this was done intentionally. Maybe it was unimplemented in Daggerfall too, but I've never seen any comment online saying this.

**Comment by Interkarma** [comment]
Allofich would have almost certainly reverse engineered the saving throw formula. But this comes also with his intentional refactoring to handle combinations of Critical Weakness and Immunity, so bonuses from Willpower might have been accidently omitted during refactor.

I've searched back through my conversations with Allofich as best as I can, and can't locate any discussion around Willpower being omitted from saving throws intentionally, so very possibly just forgotten as you say.

I'll add this one to the base SavingThrow formula now. It should come after perfect natural immunity check (i.e. Immunity-level resistance) and before clamping saving throw to 5-95 to roll.
