### ISSUE TITLE
Boethiah index points to Clavicus Vile data (0.13.1)

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2259]
If you use the "Boethiah" faction in a quest, the sprite and descriptor (terrible child) will be Clavicus Vile's. The name will be Boethiah.

On the other hand, if you use the "Clavicus Vile" faction in a quest, the sprite and descriptor (terrible child) will be Clavicus Vile's, and the name will be Clavicus Vile.

Using freshly-downloaded DaggerfallGameFiles from DFWorkshop.

**Comment by Interkarma** [comment]
Just a quick first pass on this one. In Quests-Factions table, "Clavicus_Vile" uses ID 1 and "Boethiah" uses ID 10.

    Clavicus_Vile,             0, -1, 1
    Boethiah,                  0, -1, 10

Checking these off against FACTION.TXT shows the following data for each.

    #1
    type: 0
    name: Clavicus Vile
    rep: 0
    summon: -1
    region: -1
    power: 50
    flags: 1
    enemy: 25
    face: -1
    race: -1
    flat: 175 2
    sgroup: 6
    ggroup: 2
    minf: 20
    maxf: 90

    #10
    type: 0
    name: Boethiah
    rep: 0
    summon: -1
    region: -1
    power: 45
    flags: 1
    enemy: 106
    enemy: 25
    face: -1
    race: -1
    flat: 175 2
    sgroup: 6
    ggroup: 2
    minf: 20
    maxf: 90

Note they both use flat 175 2, which is Clavicus Vile.

![image](https://user-images.githubusercontent.com/10426244/136902997-373f4281-4f6e-44ba-8202-f97e14c5644e.png)

ID 10 should use flat 175 1, which is Boethiah.

![image](https://user-images.githubusercontent.com/10426244/136903254-63ed9bf7-2388-4c4e-8017-d5a85561a85f.png)

I _think_ fixing that flat index in StreamingAssets/Factions/FACTION.TXT will also fix descriptor index, but this isn't fresh in my mind right now. By any chance Jay could you try changing the "flat" field under ID 10 to "175 1" in your local FACTION.TXT and let me know if that fixes both in your test case?

If it fixes both, I can patch this in FACTION.TXT very quickly. Otherwise will need to look into descriptor separately when I can.

**Comment by JayH2971** [comment]
That did it! Yes, we get the Boethiah sprite and "dark warrior" now. Hooray! :smile:

**Comment by JayH2971** [comment]
One of the things I'm doing now is documenting factions and groups in the quest system, so if any more errors show up, I'll be seeing them in the future. We won't have to worry about mismatched results like this much longer.

**Comment by Interkarma** [comment]
Great! Thanks for getting back so fast. :)

Even though it's a simple change, I'll keep this one open until I finish the 0.13 preview stage. I want to keep that focused on the rendering changes, after which I'll start merging other general fixes again.
