### ISSUE TITLE
0.13.1: Quest item does not become "permanent" upon enemy death

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2262]
Custom quests that attempt to convert a quest item into "permanent" state will not achieve it if "permanent" is linked to a "killed foe" condition. The following quest script is used:

> _kill2_ task:
>    killed _frenemy_
>    make _reward_ permanent
    
When the enemy dies, the item retains its green background.

This zip file includes Save888, which requires you to kill the enemy at the end of the hallway who holds the item, as well as the quest file.
[QuestItemStaysGreen.zip](https://github.com/Interkarma/daggerfall-unity/files/7423511/QuestItemStaysGreen.zip)

**Comment by BadLuckBurt** [comment]
The UID of the quest item has changed by the time that EnemyDeath.CompleteDeath() starts to transfer the enemy's inventory to the lootpile. The quest UID is still intact so I'm trying to track down where the item's UID changes atm. 

Depending on what I find, the solution will either be to update the item's UID in the quest action or make sure the item's UID doesn't change.

```
EnemyDeath.CompleteDeath() - found quest item with item.UID: 33569042

ItemCollection.TransferAll() - Transferring quest item with UID: 33569042 
ItemCollection.TransferAll() - Quest UID: 33568744 

QuestAction MakePermanent - Item UID = 33568745 
QuestAction MakePermanent - Quest UID = 33568744
```

**Comment by Interkarma** [comment]
The problem here is how the virtual quest Item lifecycle is handled relative to the DaggerfallUnityItem. In some cases the DaggerfallUnityItem tracked by Item is transferred and in some cases it's reinstantiated/cloned with a new UID. Depending on process this can lead to permanent status becoming desynced.
As this could happen in a few cases, and desynced permanent status can already be in save data (like in Jay's save above), I've opted to fix this in a low-impact way by fixing permanent status when player picks up item.
The item on slain foe will still have green background in corpse loot container, but it will be patched back to permanent when player picks up item. Tested in save attached to issue.
This should workaround most (if not all) cases of this problem and not cause any regressions.
