### ISSUE TITLE
[0.13.2b] Flashing UI

### ISSUE THREAD

**Issue by Tharn** [Interkarma/daggerfall-unity#2265]
**Describe the bug**
If I go into the "Controls" menu and then back out to the pause menu, there is a brief moment of the UI flashing magenta.
The same thing happens if I Alt-Tab out of the game and later return to it. The UI flashes for just a few frames in this case.

I was unable to capture this with a screenshot.

**To Reproduce**
1. Go to Pause Menu
2. Click on Controls
3. Return to Pause Menu
4. UI Flashes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Version 0.13.2 beta
 - Borderless Fullscreen

**Comment by Interkarma** [comment]
Hey there. :) I'm not able to reproduce this and have never observed it in any version of Daggerfall Unity.

If you have "ExclusiveFullscreen=True" configured in settings.ini, try setting this back to False. There might be something odd happening related to driver or Unity runtime as things page in and out of graphics memory with exclusive fullscreen.

Otherwise, the usual thing is to try a clean setup from DaggerfallGameFiles with no mods and delete/rename settings.ini. If that helps, then incrementally restore mods and settings until the breaking change is identified.

Help & Support on forums might be a better fit for troubleshooting this one.

https://forums.dfworkshop.net/

**Comment by Tharn** [comment]
I wiped the Settings folder and started fresh with a vanilla install of 0.13.2 beta and Daggerfall. I still get this flicker as soon as I turn on fullscreen in DFU options, which I think enables borderless. Exclusive Fullscreen is off in settings.ini. Playing windowed works fine.

This started happening with 0.13.2 only, 0.12.2 doesn't have this issue.
