### ISSUE TITLE
Rappel mode does not negate fall damage

### ISSUE THREAD

**Issue by extract** [Interkarma/daggerfall-unity#2275]
**Describe the bug**
Rappel mode does not negate fall damage. If you rappel down a building without going to climbing mode you will still get hurt as much as just falling.
Rappel is also slower than climbing down. (is this same in the DF?)

**To Reproduce**
1. Climb up a building/wall.
2. Step backwards to initiate rappel mode.
3. Keep rappel mode all the way down to ground.
4. Get hurt.

**Expected behavior**
Negated fall damage. Or change from rappel to climbing by default. (I thought rappel would be faster in theory.)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - DFU Version 0.13.4

**Additional context**
Never played original Daggerfall but I feel this should be fixed eitherway.

**Comment by KABoissonneault** [comment]
Rappel wasn't in the original game. Honestly not a fan of how the feature works in general. I wish it was replaced with just auto-climb if you go down a wall while facing it.

**Comment by Interkarma** [comment]
Hey there. :) This issue is related to below on forums, I'll close as a duplicate.

https://forums.dfworkshop.net/viewtopic.php?t=4846

Rappel mode should not continue all the way to ground. When this function works, you should transition into climbing mode momentarily after backing over edge. As a workaround, try releasing "back" key briefly after rappel initiates. I find this helps character attach to wall and resume climb mode rather than rappel reactivating all the way to ground (same as falling).

If you want a more classic climbing experience, disable Advanced Climbing in settings. This was enabled by default for testing during alpha/beta stages, but should be disabled by default now we're approaching release. I've quickly made that change now before I forget.

I'm seriously considering deprecating rappel mode as I did with ceiling hanging. Advanced Climbing is a fun addition to the game, but it added lots of small problems that required lots of fixes, and might not make the final cut in its current form.
