### ISSUE TITLE
Alik'r Fighter Guilds (Mosques) are not holy places

### ISSUE THREAD

**Issue by theMadness** [Interkarma/daggerfall-unity#2347]
According to https://en.uesp.net/wiki/Daggerfall:Alik%27r the fighter guilds in the Alik'r region should be holy places and damage Vampires, I'm not seeing that happening.

**Comment by Interkarma** [comment]
Hey there. :) The information on UESP is not always reliable. If this is confirmed to be something that happens in classic, then we might consider it an issue in DFU.

If this does happen in classic, we'd also need to determine if seems intentional or not. Classic Daggerfall often produces incorrect outcomes due to bugs on its end, and this might be such an issue.

I'll leave this open and listen to feedback before taking any action. Cheers.

**Comment by theMadness** [comment]
I did double check in Myrkwasa, according to the info in https://en.uesp.net/wiki/Daggerfall:Fighters_Guild#Fighters_Guild_Overview, and Fighter Trainers will indeed damage you as a Vampire. But the aforementioned article is imprecise.

Thank you for indulging me :)

**Comment by Interkarma** [comment]
Wonderful, thanks for testing! I'll dig into this more when I can

**Comment by Interkarma** [comment]
Testing this in DFU, holy damage is correctly applied in Alik'r Fighters guilds to vulnerable characters. This is handled in PlayerEnterExit using `Fighter_Trainers` to check if player is in a holy place.

https://github.com/Interkarma/daggerfall-unity/blob/0f5b3d473d200bb6b886915f2654f59e878f0acc/Assets/Scripts/Game/PlayerEnterExit.cs#L1428

It seems this handling was added some time ago, the check exists as far back as 2019.

Thanks for raising. :)
