### ISSUE TITLE
0.13.5, "Generic Temple" is used in dialogue

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2393]
Quest reference: A Mix-Up, [https://en.uesp.net/wiki/Daggerfall:A_Mix-Up](https://en.uesp.net/wiki/Daggerfall:A_Mix-Up)

The priest NPC is defined as [follows](https://github.com/Interkarma/daggerfall-unity/blob/1b3bc813c0c332d5467622b61c4d6d84927d59a3/Assets/StreamingAssets/Quests/K0C00Y06.txt#L853): 

> Person _priest_ factiontype Temple local anyInfo 1014

This person can be assigned to the faction "Generic Temple," which can appear in dialogue later:

![unknown](https://user-images.githubusercontent.com/37541932/179998427-3a16089a-ebd1-4812-aa1e-8480b53e1c33.png)

Perhaps the person could be forcefully assigned to a named temple instead?

**Comment by KABoissonneault** [comment]
You're right. `Person.GetFactionTypeFactionID` for `Temple` will go to `GetRandomFactionOfType`, which itself will read through all factions in FACTION.TXT with type "facTEMPLE". 
I think it's fine to reject Generic Temple (faction 450) there. 
Note that Generic Knightly Order doesn't have this issue, because there's no "Knightly Order" faction type, so you can't assign it to a Person there.
