### ISSUE TITLE
0.15.2: Books text self-overwrite when retro mode 4:3 aspect ratio is selected

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#2512]
When retro mode and aspect ratio 4:3 are enabled, some book text lines overwrite others.

Book scrolling doesn't change what lines overwrite others.
It does not happen with free or 16:10 aspect ratio.
It also happens with localized books.

Screenshot of King Edwards part 3:

![Capture d’écran du 2023-04-25 18-46-44](https://user-images.githubusercontent.com/1211431/234347862-6c9496c5-b8a8-4fed-98ab-a97dd46cd00d.jpg)

French version of the same book, with soft wrap:

![Capture d’écran du 2023-04-25 18-32-01](https://user-images.githubusercontent.com/1211431/234349347-e50ec309-7267-4e15-91e5-844b81bb57bd.jpg)

**Desktop:**

 - OS: Linux
 - Version Linux Mint 21.1
 - screen resolution 1920x1080

**Comment by petchema** [comment]
It seems to happen more often with soft wrapped text, most likely because more lines are filled to their max.
I'm uploading this the book if it helps with testing:

[BOK00102-LOC.txt](https://github.com/Interkarma/daggerfall-unity/files/11325573/BOK00102-LOC.txt)

**Comment by Interkarma** [comment]
The core problem here is those text rows are too long in book input text. See the below and note how second row is overlong.

![image](https://user-images.githubusercontent.com/10426244/234420488-ab77193c-11a6-40c1-b401-367aa4fb5257.png)

At present, DFU's multiline labels soft-wrap text without adding line breaks, so the following line overlaps. In classic, these long lines would overflow the right-hand margin.

I'll make a change so that overlong rows overflow in DFU like they do in classic. This at least makes it more obvious that problem results from source text, not the book reader itself.

DFU inherits a lot of poorly formatted books from classic game data as these were exported directly. There needs to be a general pass on books to fix several things, including formatting. Now that books are just plain text, books are open for anyone to send a PR to fix formatting issues in the source text.
