### ISSUE TITLE
1.0: Person fails to appear in "where is" talk UI for quest

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2604]
Problem description:

User reports playing Azura's quest (t0c00y00) and Meridia's quest (10c00y00) and being unable to find the reward giver. Reward giver does not show up in Talk UI when asking peasants for location. The quest journal does not say where the reward giver is (which could be an alternate fix but this is a deeper engine issue). Not known when this problem began occurring, but this quest did function properly back during quest fixing, around 0.11.

Steps to reproduce:

1. startquest t0c00y00 or 10c00y00

2. Go to dungeon and kill enemy, then travel to indicated town in travel log.

3. Ask peasants to find person who gives reward. Person does not appear in the Talk UI options. Person _does_ appear in Talk UI after you enter the reward giver's house once.

**Comment by John-Leitch** [comment]
I've reproduced this locally. Not familiar with this code, but it looks (indirectly) related to this in `TalkManager`: 

```cs
// only make it available for talk if...
if (!dialogPartnerIsSamePersonAsPersonResource &&   // Dialog partner is not the same person as the person resource talked about
    questResourceInfo.Value.availableForDialog &&   // It is not "hidden" by dialog link command
    questResourceInfo.Value.hasEntryInWhereIs &&    // It is meant to have an entry in the where is section (currently this is always true, TODO: check if we can get rid of this)
    IsPlayerInSameLocationWorldCell)                // If person resource is in same world map location as player
{
    listTopicPerson.Add(item);
}
```

Every condition evaluates to `true`, except `IsPlayerInSameLocationWorldCell`, which is `false`. Here's the code where I would expect it to be set to `true`:

```cs
/* - note: found a different way to do it via mapId
try
{
    IsPlayerInSameLocationWorldCell = ((Questing.Person)questResourceInfo.Value.questResource).IsPlayerInSameLocationWorldCell();
}
catch (Exception e)
{
}*/

Symbol assignedPlaceSymbol = person.GetAssignedPlaceSymbol();

if (assignedPlaceSymbol != null)
{
    Quest quest = GameManager.Instance.QuestMachine.GetQuest(questID);
    Place assignedPlace = quest.GetPlace(assignedPlaceSymbol);  // Gets actual place resource
    if (assignedPlace.SiteDetails.mapId == GameManager.Instance.PlayerGPS.CurrentMapID)
        IsPlayerInSameLocationWorldCell = true;
}
```

The commented out code is especially of interest. I haven't confirmed, but it seems like this might be the regression. Finally, to elaborate on the erroneous state, `IsPlayerInSameLocationWorldCell` is not set to `true` because `GetAssignedPlaceSymbol` returns `null`. I'd like to dig further into this and submit a PR, but it might be a couple days.

**Comment by John-Leitch** [comment]
Okay, turns out reverting to the commented out code does not work. `IsPlayerInSameLocationWorldCell` calls `Quest.GetPlace` with `lastAssignedPlaceSymbol`, which is `null`. In turn, `GetPlace` returns `null`, resulting in `IsPlayerInSameLocationWorldCell` returning `false`.

**Comment by JayH2971** [comment]
It turns out the named NPC shows up in the "Tell Me About," not in the "Where Is" section. The "Tell Me About" provides the building name where the NPC is placed.

It's an unusual setup, but the quest works fine. No fix needed.

**Comment by KABoissonneault** [comment]
The NPC appears just fine, but it appears in the "Tell Me About" section rather than the usual "Where Is? -> People" section.

![image](https://github.com/Interkarma/daggerfall-unity/assets/5789925/bf8f8cbb-c98f-41d1-9814-8b1a8411f3d3)

It's not terribly intuitive, but it matches classic. It's not really a DFU issue. 

There is one issue I think where the NPC does appear under Where Is if the zone is loaded once, as mentioned in the OP

![image](https://github.com/Interkarma/daggerfall-unity/assets/5789925/7be6dc4a-890b-4b24-9cd5-a6d606b21bad)

That part we could fix, but it's pretty minor
